#!/usr/bin/env python3
"""
Regenerate assets/pricing-data.js from the yearly pricing-list PDFs.

Usage:
    python3 tools/extract_pricing.py

Requires `pdftotext` (poppler):  brew install poppler

It reads the CUSTOM section of each pricing list (Classic / Signature / Elite),
pulls every CUS* inventory line, and writes a single flat
{level: {INVENTORY_ID: price}} map plus a shared description map.

Inventory IDs are identical across the three levels — only prices change — so
the app builds the ID it needs from the rep's inputs and looks the price up.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEVELS = ["classic", "signature", "elite"]
PDF = "{level}-pricing-2026.pdf"
EFFECTIVE = "June 1st, 2026"

LINE = re.compile(r"\s*(CUS[A-Z0-9]+)\s{2,}(.+?)\s{2,}\$?([\d,]+\.\d{2})\s*$")


def pdf_text(path: Path) -> str:
    return subprocess.run(
        ["pdftotext", "-layout", str(path), "-"],
        check=True, capture_output=True, text=True,
    ).stdout


def custom_section(text: str) -> list[str]:
    """Everything from the CUSTOM divider page to the end of the document."""
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        if ln.strip() == "CUSTOM":
            return lines[i:]
    raise SystemExit("CUSTOM section header not found")


def parse(level: str) -> tuple[dict[str, float], dict[str, str]]:
    prices, descs = {}, {}
    for ln in custom_section(pdf_text(ROOT / PDF.format(level=level))):
        m = LINE.match(ln)
        if not m:
            continue
        code, desc, price = m.group(1), m.group(2).strip(), float(m.group(3).replace(",", ""))
        if code in prices and prices[code] != price:
            print(f"  ! {level}: duplicate {code} with differing prices", file=sys.stderr)
        prices[code] = price
        descs[code] = desc
    return prices, descs


def main() -> None:
    levels, descriptions = {}, {}
    for level in LEVELS:
        prices, descs = parse(level)
        levels[level] = prices
        descriptions.update(descs)
        print(f"{level}: {len(prices)} custom line items")

    keys = [set(v) for v in levels.values()]
    if not all(k == keys[0] for k in keys):
        print("! inventory IDs differ between levels — check the PDFs", file=sys.stderr)

    body = json.dumps(
        {"effective": EFFECTIVE, "levels": levels, "descriptions": descriptions},
        indent=1, sort_keys=True,
    )
    out = ROOT / "assets" / "pricing-data.js"
    out.write_text(
        "// AUTO-GENERATED by tools/extract_pricing.py — do not edit by hand.\n"
        "// Source: {classic,signature,elite}-pricing-2026.pdf, CUSTOM section.\n"
        f"window.PRICING_DATA = {body};\n"
    )
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
